-- ============================================================
-- BLC Affiliate OS — Supabase Schema
-- Run this entire file in Supabase SQL Editor
-- ============================================================

-- Drop old outreach table and recreate with full pipeline schema
DROP TABLE IF EXISTS outreach CASCADE;

CREATE TABLE outreach (
  id                   UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  handle               TEXT NOT NULL,
  name                 TEXT,
  email                TEXT,
  product_category     TEXT,
  follower_count       BIGINT,
  last_30d_gmv         NUMERIC(12,2),
  avg_engagement       TEXT,
  estimated_post_rate  TEXT,
  profile_url          TEXT,

  -- Pipeline stage
  status               TEXT NOT NULL DEFAULT 'drafted',
  -- drafted | sent | replied | evaluating | counter_offered | signed | ghosted

  -- Outreach email (generated by Claude)
  generated_email      TEXT,
  sender               TEXT,

  -- After reply
  asked_rate           NUMERIC(10,2),

  -- Evaluation (Creator Evaluation System)
  on_camera            TEXT,       -- yes | no
  feels_natural        TEXT,       -- natural | forced
  viral_potential      TEXT,       -- yes | maybe | no
  tier                 TEXT,       -- A | B | C
  evaluation_notes     TEXT,

  -- Counter offer
  counter_offer_amount NUMERIC(10,2),
  counter_offer_email  TEXT,

  -- Signing details (populated when status = signed)
  video_count          INTEGER,
  start_date           DATE,

  created_at           TIMESTAMPTZ DEFAULT NOW(),
  updated_at           TIMESTAMPTZ DEFAULT NOW()
);

-- Roster table: active affiliate database (unchanged)
CREATE TABLE IF NOT EXISTS roster (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  handle TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT 'TikTok',
  niche TEXT,
  followers INTEGER,
  content_style TEXT,
  audience_demographics TEXT,
  content_submitted INTEGER DEFAULT 0,
  gmv DECIMAL(12,2) DEFAULT 0,
  commission_rate DECIMAL(5,2) DEFAULT 15,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'paused')),
  email TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE TRIGGER update_outreach_updated_at
  BEFORE UPDATE ON outreach
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE TRIGGER update_roster_updated_at
  BEFORE UPDATE ON roster
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- App settings (persists OAuth tokens across server restarts)
CREATE TABLE IF NOT EXISTS app_settings (
  key   TEXT PRIMARY KEY,
  value JSONB
);
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;

-- Disable RLS (internal tool — no user auth layer)
ALTER TABLE outreach DISABLE ROW LEVEL SECURITY;
ALTER TABLE roster DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- Roster v2 — run these ALTER statements after initial setup
-- ============================================================
ALTER TABLE roster ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS tier TEXT;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS video_count INTEGER;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS per_vid_rate NUMERIC(10,2);
ALTER TABLE roster ADD COLUMN IF NOT EXISTS top_videos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS blc_videos JSONB DEFAULT '[]'::jsonb;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS posting_schedule JSONB DEFAULT '[]'::jsonb;
ALTER TABLE roster ADD COLUMN IF NOT EXISTS creator_assessment TEXT;

-- Drop the old 3-value status CHECK and replace with 4-value version
ALTER TABLE roster DROP CONSTRAINT IF EXISTS roster_status_check;
ALTER TABLE roster ADD CONSTRAINT roster_status_check
  CHECK (status IN ('active', 'inactive', 'paused', 'watching'));

-- Roster affiliate type
ALTER TABLE roster ADD COLUMN IF NOT EXISTS affiliate_type TEXT DEFAULT 'paid'
  CHECK (affiliate_type IN ('paid', 'free'));

-- ============================================================
-- Outreach follow-up tracking
-- ============================================================
-- Payment tracking (50% deposit when signed)
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS payment_sent      BOOLEAN DEFAULT FALSE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS payment_sent_date DATE;

ALTER TABLE outreach ADD COLUMN IF NOT EXISTS sent_date          DATE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS followup1_date     DATE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS followup1_sent     BOOLEAN DEFAULT FALSE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS followup1_sent_date DATE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS followup2_date     DATE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS followup2_sent     BOOLEAN DEFAULT FALSE;
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS followup2_sent_date DATE;

-- ============================================================
-- Content Lab — saved scripts
-- ============================================================
CREATE TABLE IF NOT EXISTS scripts (
  id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  creator_id     UUID,
  creator_handle TEXT,
  product_focus  TEXT,
  script_length  TEXT,
  content        TEXT NOT NULL,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE scripts DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE scripts TO anon;
GRANT ALL ON TABLE scripts TO authenticated;

-- ============================================================
-- Roster — add 'completed' status (videos done, final payment pending)
-- Run this in a new Supabase SQL editor tab
-- ============================================================
ALTER TABLE roster DROP CONSTRAINT IF EXISTS roster_status_check;
ALTER TABLE roster ADD CONSTRAINT roster_status_check
  CHECK (status IN ('active', 'inactive', 'paused', 'watching', 'onboarding', 'completed'));
